name: Create published=true pull request

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: korosuke613/zenn-metadata-updater-action@19ec37916c7ff20def217947319d33768b76c3c3
        with:
          published: true

  not-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: korosuke613/zenn-metadata-updater-action@19ec37916c7ff20def217947319d33768b76c3c3
        with:
          published: true
          dry-run: true
      - run: |
          git add -A
          git -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
              -c user.name='github-actions[bot]' \
              commit -m "hoge"
      - uses: korosuke613/zenn-metadata-updater-action@19ec37916c7ff20def217947319d33768b76c3c3
        with:
          published: true
