name: Create published=true pull request
on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: korosuke613/zenn-metadata-updater-action@0b4c9aaf59f94877f66653072af43ce5bf0bbd91
        with:
          published: true
          force-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
