name: Validate

on: 
  pull_request:

permissions:
  contents: read

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: korosuke613/zenn-metadata-updater-action@release-please--branches--main--components--typescript-action
        id: action
        with:
          validate-only: true
        continue-on-error: true
      - if: ${{ steps.action.outcome == 'failure' }}
        run: echo "Success"
      - if: ${{ steps.action.outcome == 'success' }}
        run: |
          echo "Failure"
          exit 1
